import { type OverheadEmployee } from '../lib/overheadRepository';

// Local type used in Pipeline component
export type OverheadRow = {
  id?: string; // Optional for new entries
  department: string;
  employee: string;
  role: string;
  location?: 'Canada' | 'US'; // Employee location for burden calculation
  annualSalary: number;
  allocationPercent: number;
  startDate?: string;
  endDate?: string;
  monthly: { [month: string]: number };
};

// Convert OverheadRow to OverheadEmployee for database operations
export const overheadRowToEmployee = (row: OverheadRow): Omit<OverheadEmployee, 'created_at' | 'updated_at'> => {
  return {
    id: row.id || '', // Will be generated by database if empty
    department: row.department,
    employee_name: row.employee,
    role: row.role,
    location: row.location || null,
    annual_salary: row.annualSalary,
    allocation_percent: row.allocationPercent,
    start_date: row.startDate || null,
    end_date: row.endDate || null,
    monthly_allocations: row.monthly,
    created_by: null, // Will be set by the database functions
    updated_by: null  // Will be set by the database functions
  };
};

// Convert OverheadEmployee to OverheadRow for local use
export const employeeToOverheadRow = (employee: OverheadEmployee): OverheadRow => {
  return {
    id: employee.id,
    department: employee.department,
    employee: employee.employee_name,
    role: employee.role,
    location: employee.location || undefined,
    annualSalary: employee.annual_salary,
    allocationPercent: employee.allocation_percent,
    startDate: employee.start_date || undefined,
    endDate: employee.end_date || undefined,
    monthly: employee.monthly_allocations
  };
};

// Convert array of OverheadRows to OverheadEmployees
export const overheadRowsToEmployees = (rows: OverheadRow[]): Array<Omit<OverheadEmployee, 'created_at' | 'updated_at'>> => {
  return rows.map(overheadRowToEmployee);
};

// Convert array of OverheadEmployees to OverheadRows
export const employeesToOverheadRows = (employees: OverheadEmployee[]): OverheadRow[] => {
  return employees.map(employeeToOverheadRow);
};

// Generate a temporary ID for new overhead rows (before saving to database)
export const generateTempId = (): string => {
  return `temp_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
};

// Check if an overhead row is new (not yet saved to database)
export const isNewOverheadRow = (row: OverheadRow): boolean => {
  return !row.id || row.id.startsWith('temp_');
};

// Validate overhead row data
export const validateOverheadRow = (row: OverheadRow): { isValid: boolean; errors: string[] } => {
  const errors: string[] = [];

  if (!row.department.trim()) {
    errors.push('Department is required');
  }

  if (!row.employee.trim()) {
    errors.push('Employee name is required');
  }

  if (!row.role.trim()) {
    errors.push('Role is required');
  }

  if (row.annualSalary < 0) {
    errors.push('Annual salary must be non-negative');
  }

  if (row.allocationPercent < 0 || row.allocationPercent > 100) {
    errors.push('Allocation percent must be between 0 and 100');
  }

  if (row.startDate && row.endDate && new Date(row.startDate) > new Date(row.endDate)) {
    errors.push('Start date must be before end date');
  }

  return {
    isValid: errors.length === 0,
    errors
  };
};
