// Rate mapping from Salt Rate Card 2025 CSV data
export const RATE_MAPPING_2025: { [key: string]: { [key: string]: number } } = {
  'Labatt': {
    // Accounts
    'Production Coordinator': 65,
    'Production Executive': 80,
    'Production Manager': 100,
    'Production Supervisor': 120,
    'Production Director': 150,
    'Sr. Production Director': 200,
    'Managing Director': 240,
    'Vice President': 270,
    'Sr Vice President': 300,
    'Executive Vice President': 325,
    // Design
    'Designer': 140,
    'Sr Designer': 155,
    'Asc Design Director': 175,
    'Design director': 200,
    'Sr Design Director': 225,
    'VP, Design': 250,
    '3D Designer': 170,
    'Sr 3D Designer': 200,
    'Associate 3D Design Director': 225,
    '3D Design Director': 250,
    // Creative
    'Copywriter': 130,
    'Conceptor': 140,
    'Creative': 140, // Maps to same rate as Conceptor
    'Associate Creative Director': 200,
    'Creative Director': 250,
    'Group Creative Director': 300,
    'Executive Creative Director': 325,
    'SVP, Creative': 350,
    // Studio
    'Producer': 150,
    'Sr Producer': 185,
    'Editor': 185,
    'Sr Editor': 200,
    'Animator': 150,
    'Colorist': 250,
    'Post Production Lead': 150,
    'Head of Production': 200,
    'VP, Studio': 250,
    // Strategy
    'VP, Strategy & Planning': 300,
    'Sr Director, Strategy / Planning': 250,
    'Director, Strategy / Planning': 225,
    'Sr Strategist / Planner': 185,
    'Strategist / Planner': 165,
    'Jr Strategist / Planner': 125,
    // Omni Shopper
    'MD, Shopper': 250,
    'Sr. Director, Shopper': 225,
    'Account Director, Shopper': 175,
    'Account Supervisor, Shopper': 145,
    'Account Manager, Shopper': 125,
    'Account Executive, Shopper': 95,
    'Coordinator, Shopper': 85,
    'Executive Creative Director, Shopper': 300,
    'Creative Director, Shopper': 250,
    'Associate Creative Director, Shopper': 200,
    'Sr. Design Director, Shopper': 225,
    'Art Director, Shopper': 200,
    'Sr. Designer, Shopper': 155,
    'Designer, Shopper': 140,
    // Creator
    'Coordinator, Creator': 90,
    'Specialist, Creator': 110,
    'Manager, Creator': 130,
    'Supervisor, Creator': 150,
    'Associate Director, Creator': 175,
    'Director, Creator': 210,
    'MD, Creator': 250,
    // Social
    'Coordinator, Social': 85,
    'Specialist, Social': 100,
    'Manager, Social': 130,
    'Supervisor, Social': 150,
    'Director, Social': 210,
    'Managing Director, Social': 250,
    // Media
    'Coordinator, Media': 90,
    'Coordinator, SEM': 90,
    'Executive, Media': 110,
    'Manager, Media': 135,
    'Manager, SEM': 155,
    'Supervisor, Media': 155,
    'Asc Director, Media': 180,
    'Director, Media': 210,
    'VP, Media': 255,
    // Digital
    'Jr. Developer': 95,
    'Mid Developer': 150,
    'Sr. Developer': 195,
    'UX Designer': 150,
    'Sr UX Designer': 175,
    'Jr Digital Project Manager': 95,
    'Digital Project Manager': 135,
    'Sr Digital Project Manager': 155,
    'Director, Digital': 210,
    'VP, Digital': 255,
    'SVP, Digital': 300,
    'Creative Technologist': 200
  },
  'RBC': {
    // Accounts
    'Account Coordinator': 40,
    'Account Executive': 60,
    'Account Manager': 70,
    'Account Supervisor': 90,
    'Production Coordinator': 40,
    'Production Executive': 50,
    'Production Manager': 60,
    'Production Supervisor': 70,
    'Production Director': 90,
    'Sr. Production Director': 115,
    'Account Director': 100,
    'Senior Account Director': 115,
    'Managing Director': 130,
    'Vice President': 145,
    'Sr Vice President': 155,
    'Executive Vice President': 175,
    // Design
    'Designer': 75,
    'Sr Designer': 80,
    'Asc Design Director': 82.5,
    'Design director': 85,
    'Sr Design Director': 90,
    'VP, Design': 140,
    '3D Designer': 90,
    'Sr 3D Designer': 85,
    'Associate 3D Design Director': 100,
    '3D Design Director': 110,
    // Creative
    'Copywriter': 75,
    'Conceptor': 75,
    'Creative': 75, // Maps to same rate as Conceptor
    'Associate Creative Director': 85,
    'Creative Director': 110,
    'Group Creative Director': 140,
    'Executive Creative Director': 140,
    'SVP, Creative': 170,
    // Studio
    'Producer': 80,
    'Sr Producer': 100,
    'Editor': 100,
    'Sr Editor': 120,
    'Animator': 80,
    'Colorist': 120,
    'Post Production Lead': 80,
    'Head of Production': 100,
    'VP, Studio': 130,
    // Strategy
    'VP, Strategy & Planning': 140,
    'Sr Director, Strategy / Planning': 120,
    'Director, Strategy / Planning': 110,
    'Sr Strategist / Planner': 95,
    'Strategist / Planner': 85,
    'Jr Strategist / Planner': 75,
    // Omni Shopper
    'MD, Shopper': 120,
    'Sr. Director, Shopper': 115,
    'Account Director, Shopper': 85,
    'Account Supervisor, Shopper': 70,
    'Account Manager, Shopper': 60,
    'Account Executive, Shopper': 50,
    'Coordinator, Shopper': 45,
    'Executive Creative Director, Shopper': 300,
    'Creative Director, Shopper': 250,
    'Associate Creative Director, Shopper': 200,
    'Sr. Design Director, Shopper': 225,
    'Art Director, Shopper': 200,
    'Sr. Designer, Shopper': 155,
    'Designer, Shopper': 140,
    // Creator
    'Coordinator, Creator': 45,
    'Specialist, Creator': 65,
    'Manager, Creator': 70,
    'Supervisor, Creator': 75,
    'Associate Director, Creator': 100,
    'Director, Creator': 120,
    'MD, Creator': 130,
    // Social
    'Coordinator, Social': 45,
    'Specialist, Social': 60,
    'Manager, Social': 65,
    'Supervisor, Social': 70,
    'Director, Social': 120,
    'Managing Director, Social': 125,
    // Media
    'Coordinator, Media': 50,
    'Coordinator, SEM': 50,
    'Executive, Media': 75,
    'Manager, Media': 75,
    'Manager, SEM': 85,
    'Supervisor, Media': 85,
    'Asc Director, Media': 100,
    'Director, Media': 120,
    'VP, Media': 140,
    // Digital
    'Jr. Developer': 50,
    'Mid Developer': 75,
    'Sr. Developer': 95,
    'UX Designer': 75,
    'Sr UX Designer': 85,
    'Jr Digital Project Manager': 50,
    'Digital Project Manager': 70,
    'Sr Digital Project Manager': 80,
    'Director, Digital': 100,
    'VP, Digital': 130,
    'SVP, Digital': 150,
    'Creative Technologist': 100
  },
  'Toyota Retainer': {
    // Accounts
    'Account Coordinator': 80,
    'Account Executive': 80,
    'Account Manager': 90,
    'Account Supervisor': 115,
    'Account Director': 140,
    'Senior Account Director': 140,
    'Managing Director': 175,
    'Vice President': 175,
    'Sr Vice President': 200,
    'Executive Vice President': 200,
    // Design
    'Designer': 105,
    'Sr Designer': 110,
    'Asc Design Director': 130,
    'Design director': 160,
    'Sr Design Director': 180,
    'VP, Design': 275,
    '3D Design Director': 225,
    // Creative
    'Copywriter': 120,
    'Conceptor': 140,
    'Creative': 140, // Maps to same rate as Conceptor
    'Associate Creative Director': 200,
    'Creative Director': 225,
    'Group Creative Director': 275,
    'Executive Creative Director': 275,
    'SVP, Creative': 325,
    // Studio
    'Producer': 125,
    'Sr Producer': 125,
    'Editor': 125,
    'Sr Editor': 175,
    'Animator': 125,
    'Colorist': 200,
    'Production Coordinator': 65,
    'Post Production Lead': 125,
    'Head of Production': 175,
    'VP, Studio': 200,
    // Strategy
    'VP, Strategy & Planning': 250,
    'Sr Director, Strategy / Planning': 200,
    'Director, Strategy / Planning': 175,
    'Sr Strategist / Planner': 175,
    'Strategist / Planner': 125,
    'Jr Strategist / Planner': 75,
    // Omni Shopper
    'MD, Shopper': 250,
    'Sr. Director, Shopper': 225,
    'Account Director, Shopper': 175,
    'Account Supervisor, Shopper': 145,
    'Account Manager, Shopper': 125,
    'Account Executive, Shopper': 95,
    'Coordinator, Shopper': 85,
    'Executive Creative Director, Shopper': 300,
    'Creative Director, Shopper': 250,
    'Associate Creative Director, Shopper': 200,
    'Sr. Design Director, Shopper': 225,
    'Art Director, Shopper': 200,
    'Sr. Designer, Shopper': 155,
    'Designer, Shopper': 140,
    // Creator
    'Coordinator, Creator': 65,
    'Specialist, Creator': 110,
    'Manager, Creator': 100,
    'Supervisor, Creator': 123,
    'Associate Director, Creator': 150,
    'Director, Creator': 175,
    'MD, Creator': 225,
    // Social
    'Coordinator, Social': 65,
    'Specialist, Social': 75,
    'Manager, Social': 100,
    'Supervisor, Social': 125,
    'Director, Social': 175,
    'Managing Director, Social': 210,
    // Digital
    'Jr. Developer': 95,
    'Mid Developer': 150,
    'Sr. Developer': 195,
    'UX Designer': 150,
    'Sr UX Designer': 175,
    'Jr Digital Project Manager': 95,
    'Digital Project Manager': 135,
    'Sr Digital Project Manager': 155,
    'Director, Digital': 210,
    'VP, Digital': 255,
    'SVP, Digital': 300,
    'Creative Technologist': 200
  },
  'Hershey Retainer': {
    // Accounts
    'Account Coordinator': 70,
    'Account Executive': 80,
    'Account Manager': 90,
    'Account Supervisor': 115,
    'Production Manager': 90,
    'Account Director': 140,
    'Managing Director': 175,
    'Vice President': 175,
    'Sr Vice President': 200,
    'Executive Vice President': 200,
    // Design
    'Designer': 120,
    'Sr Designer': 130,
    'Asc Design Director': 150,
    'Design director': 175,
    'Sr Design Director': 200,
    'VP, Design': 225,
    '3D Design Director': 200,
    // Creative
    'Copywriter': 105,
    'Conceptor': 125,
    'Creative': 125, // Maps to same rate as Conceptor
    'Associate Creative Director': 175,
    'Creative Director': 200,
    'Group Creative Director': 225,
    'Executive Creative Director': 225,
    // Strategy
    'VP, Strategy & Planning': 225,
    'Sr Director, Strategy / Planning': 175,
    'Director, Strategy / Planning': 150,
    'Sr Strategist / Planner': 125,
    'Strategist / Planner': 100,
    'Jr Strategist / Planner': 75,
    // Studio
    'Producer': 100,
    'Sr Producer': 125,
    'Editor': 125,
    'Sr Editor': 150,
    'Animator': 100,
    'Colorist': 175,
    'Post Production Lead': 100,
    'Head of Production': 150,
    'VP, Studio': 200,
    // Creator
    'Coordinator, Creator': 65,
    'Specialist, Creator': 85,
    'Manager, Creator': 100,
    'Supervisor, Creator': 115,
    'Associate Director, Creator': 140,
    'Director, Creator': 175,
    'MD, Creator': 200,
    // Social
    'Coordinator, Social': 65,
    'Specialist, Social': 75,
    'Manager, Social': 100,
    'Supervisor, Social': 115,
    'Director, Social': 175,
    'Managing Director, Social': 200,
    // Media
    'Coordinator, Media': 70,
    'Coordinator, SEM': 70,
    'Executive, Media': 85,
    'Manager, Media': 110,
    'Manager, SEM': 125,
    'Supervisor, Media': 125,
    'Asc Director, Media': 150,
    'Director, Media': 175,
    'VP, Media': 225,
    // Omni Shopper
    'MD, Shopper': 200,
    'Sr. Director, Shopper': 175,
    'Account Director, Shopper': 140,
    'Account Supervisor, Shopper': 115,
    'Account Manager, Shopper': 100,
    'Account Executive, Shopper': 80,
    'Coordinator, Shopper': 70,
    'Executive Creative Director, Shopper': 225,
    'Creative Director, Shopper': 200,
    'Associate Creative Director, Shopper': 175,
    'Sr. Design Director, Shopper': 200,
    'Art Director, Shopper': 175,
    'Sr. Designer, Shopper': 130,
    'Designer, Shopper': 120,
    'Sr. Strategist, Shopper': 125,
    // Digital
    'Jr. Developer': 95,
    'Mid Developer': 150,
    'Sr. Developer': 195,
    'UX Designer': 150,
    'Sr UX Designer': 175,
    'Jr Digital Project Manager': 95,
    'Digital Project Manager': 135,
    'Sr Digital Project Manager': 155,
    'Director, Digital': 210,
    'VP, Digital': 255,
    'SVP, Digital': 300,
    'Creative Technologist': 200
  },
  'ABI': {
    // Accounts
    'Account Coordinator': 85,
    'Account Executive': 100,
    'Account Manager': 125,
    'Account Supervisor': 150,
    'Account Director': 175,
    'Senior Account Director': 200,
    'Managing Director': 210,
    'Vice President': 225,
    'Sr Vice President': 250,
    'Executive Vice President': 275,
    // Design
    'Designer': 165,
    'Sr Designer': 175,
    'Asc Design Director': 200,
    'Design director': 225,
    'Sr Design Director': 250,
    'VP, Design': 275,
    '3D Designer': 200,
    'Sr 3D Designer': 225,
    'Associate 3D Design Director': 250,
    '3D Design Director': 250,
    // Creative
    'Copywriter': 155,
    'Conceptor': 165,
    'Creative': 165, // Maps to same rate as Conceptor
    'Associate Creative Director': 225,
    'Creative Director': 250,
    'Group Creative Director': 275,
    'Executive Creative Director': 275,
    'SVP, Creative': 325,
    // Strategy
    'VP, Strategy & Planning': 275,
    'Sr Director, Strategy / Planning': 225,
    'Director, Strategy / Planning': 200,
    'Sr Strategist / Planner': 175,
    'Strategist / Planner': 150,
    'Jr Strategist / Planner': 125,
    // Studio
    'Producer': 150,
    'Sr Producer': 185,
    'Editor': 185,
    'Sr Editor': 200,
    'Animator': 150,
    'Colorist': 250,
    'Post Production Lead': 150,
    'Head of Production': 200,
    'VP, Studio': 275,
    // Creator
    'Coordinator, Creator': 100,
    'Specialist, Creator': 125,
    'Manager, Creator': 150,
    'Supervisor, Creator': 175,
    'Associate Director, Creator': 200,
    'Director, Creator': 225,
    'MD, Creator': 275,
    // Social
    'Coordinator, Social': 100,
    'Specialist, Social': 125,
    'Manager, Social': 150,
    'Supervisor, Social': 175,
    'Director, Social': 225,
    'Managing Director, Social': 275,
    // Media
    'Coordinator, Media': 110,
    'Coordinator, SEM': 110,
    'Executive, Media': 135,
    'Manager, Media': 160,
    'Manager, SEM': 180,
    'Supervisor, Media': 180,
    'Asc Director, Media': 200,
    'Director, Media': 225,
    'VP, Media': 275,
    // Omni Shopper
    'MD, Shopper': 275,
    'Sr. Director, Shopper': 250,
    'Account Director, Shopper': 200,
    'Account Supervisor, Shopper': 175,
    'Account Manager, Shopper': 150,
    'Account Executive, Shopper': 125,
    'Coordinator, Shopper': 100,
    'Executive Creative Director, Shopper': 275,
    'Creative Director, Shopper': 250,
    'Associate Creative Director, Shopper': 225,
    'Sr. Design Director, Shopper': 250,
    'Art Director, Shopper': 225,
    'Sr. Designer, Shopper': 175,
    'Designer, Shopper': 165,
    'Sr. Strategist, Shopper': 175,
    // Digital
    'Jr. Developer': 110,
    'Mid Developer': 170,
    'Sr. Developer': 220,
    'UX Designer': 175,
    'Sr UX Designer': 190,
    'Jr Digital Project Manager': 110,
    'Digital Project Manager': 160,
    'Sr Digital Project Manager': 180,
    'Director, Digital': 225,
    'VP, Digital': 275,
    'SVP, Digital': 320,
    'Creative Technologist': 220
  },
  'Rogers': {
    // Accounts
    'Account Coordinator': 83,
    'Account Executive': 124,
    'Account Manager': 144,
    'Account Supervisor': 185,
    'Account Director': 206,
    'Senior Account Director': 237,
    'Managing Director': 268,
    'Vice President': 299,
    'Sr Vice President': 325,
    'Executive Vice President': 350,
    // Design
    'Designer': 155,
    'Sr Designer': 165,
    'Asc Design Director': 180,
    'Design director': 196,
    'Sr Design Director': 212,
    'VP, Design': 289,
    '3D Designer': 186,
    'Sr 3D Designer': 196,
    'Associate 3D Design Director': 227,
    '3D Design Director': 227,
    // Creative
    'Copywriter': 155,
    'Conceptor': 155,
    'Creative': 155, // Maps to same rate as Conceptor
    'Associate Creative Director': 196,
    'Creative Director': 227,
    'Group Creative Director': 289,
    'Executive Creative Director': 206,
    'SVP, Creative': 351,
    // Strategy
    'VP, Strategy & Planning': 289,
    'Sr Director, Strategy / Planning': 227,
    'Director, Strategy / Planning': 196,
    'Sr Strategist / Planner': 175,
    'Strategist / Planner': 155,
    'Jr Strategist / Planner': 124,
    // Studio
    'Producer': 140,
    'Sr Producer': 175,
    'Editor': 175,
    'Sr Editor': 190,
    'Animator': 140,
    'Colorist': 227,
    'Post Production Lead': 140,
    'Head of Production': 190,
    'VP, Studio': 289,
    // Creator
    'Coordinator, Creator': 90,
    'Specialist, Creator': 110,
    'Manager, Creator': 135,
    'Supervisor, Creator': 155,
    'Associate Director, Creator': 180,
    'Director, Creator': 210,
    'MD, Creator': 250,
    // Social
    'Coordinator, Social': 90,
    'Specialist, Social': 110,
    'Manager, Social': 135,
    'Supervisor, Social': 155,
    'Director, Social': 210,
    'Managing Director, Social': 250,
    // Media
    'Coordinator, Media': 95,
    'Coordinator, SEM': 95,
    'Executive, Media': 120,
    'Manager, Media': 145,
    'Manager, SEM': 165,
    'Supervisor, Media': 165,
    'Asc Director, Media': 190,
    'Director, Media': 210,
    'VP, Media': 289,
    // Omni Shopper
    'MD, Shopper': 250,
    'Sr. Director, Shopper': 227,
    'Account Director, Shopper': 180,
    'Account Supervisor, Shopper': 155,
    'Account Manager, Shopper': 135,
    'Account Executive, Shopper': 110,
    'Coordinator, Shopper': 90,
    'Executive Creative Director, Shopper': 206,
    'Creative Director, Shopper': 227,
    'Associate Creative Director, Shopper': 196,
    'Sr. Design Director, Shopper': 212,
    'Art Director, Shopper': 196,
    'Sr. Designer, Shopper': 165,
    'Designer, Shopper': 155,
    'Sr. Strategist, Shopper': 175,
    // Digital
    'Jr. Developer': 140,
    'Mid Developer': 155,
    'Sr. Developer': 196,
    'UX Designer': 155,
    'Sr UX Designer': 175,
    'Jr Digital Project Manager': 140,
    'Digital Project Manager': 135,
    'Sr Digital Project Manager': 160,
    'Director, Digital': 250,
    'VP, Digital': 300,
    'SVP, Digital': 360,
    'Creative Technologist': 240
  },
  'Standard': {
    // Accounts
    'Account Coordinator': 80,
    'Account Executive': 95,
    'Account Manager': 125,
    'Account Supervisor': 145,
    'Production Coordinator': 65,
    'Production Executive': 80,
    'Production Manager': 100,
    'Production Supervisor': 120,
    'Production Director': 150,
    'Sr. Production Director': 200,
    'Account Director': 175,
    'Senior Account Director': 200,
    'Managing Director': 240,
    'Vice President': 270,
    'Sr Vice President': 300,
    'Executive Vice President': 325,
    // Design
    'Designer': 140,
    'Sr Designer': 155,
    'Asc Design Director': 175,
    'Design director': 200,
    'Sr Design Director': 225,
    'VP, Design': 275,
    '3D Designer': 170,
    'Sr 3D Designer': 200,
    'Associate 3D Design Director': 225,
    '3D Design Director': 250,
    // Creative
    'Copywriter': 130,
    'Conceptor': 140,
    'Creative': 140, // Maps to same rate as Conceptor
    'Associate Creative Director': 200,
    'Creative Director': 250,
    'Group Creative Director': 300,
    'Executive Creative Director': 325,
    'SVP, Creative': 350,
    // Strategy
    'VP, Strategy & Planning': 300,
    'Sr Director, Strategy / Planning': 250,
    'Director, Strategy / Planning': 225,
    'Sr Strategist / Planner': 185,
    'Strategist / Planner': 165,
    'Jr Strategist / Planner': 125,
    // Studio
    'Producer': 150,
    'Sr Producer': 185,
    'Editor': 185,
    'Sr Editor': 200,
    'Animator': 150,
    'Colorist': 250,
    'Post Production Lead': 150,
    'Head of Production': 200,
    'VP, Studio': 250,
    // Creator
    'Coordinator, Creator': 90,
    'Specialist, Creator': 110,
    'Manager, Creator': 130,
    'Supervisor, Creator': 150,
    'Associate Director, Creator': 175,
    'Director, Creator': 210,
    'MD, Creator': 250,
    // Social
    'Coordinator, Social': 85,
    'Specialist, Social': 100,
    'Manager, Social': 130,
    'Supervisor, Social': 150,
    'Director, Social': 210,
    'Managing Director, Social': 250,
    // Media
    'Coordinator, Media': 90,
    'Coordinator, SEM': 90,
    'Executive, Media': 110,
    'Manager, Media': 135,
    'Manager, SEM': 155,
    'Supervisor, Media': 155,
    'Asc Director, Media': 180,
    'Director, Media': 210,
    'VP, Media': 255,
    // Omni Shopper
    'MD, Shopper': 250,
    'Sr. Director, Shopper': 225,
    'Account Director, Shopper': 175,
    'Account Supervisor, Shopper': 145,
    'Account Manager, Shopper': 125,
    'Account Executive, Shopper': 95,
    'Coordinator, Shopper': 85,
    'Executive Creative Director, Shopper': 325,
    'Creative Director, Shopper': 250,
    'Associate Creative Director, Shopper': 200,
    'Sr. Design Director, Shopper': 225,
    'Art Director, Shopper': 200,
    'Sr. Designer, Shopper': 155,
    'Designer, Shopper': 140,
    'Sr. Strategist, Shopper': 185,
    // Digital
    'Jr. Developer': 95,
    'Mid Developer': 150,
    'Sr. Developer': 195,
    'UX Designer': 150,
    'Sr UX Designer': 175,
    'Jr Digital Project Manager': 95,
    'Digital Project Manager': 135,
    'Sr Digital Project Manager': 155,
    'Director, Digital': 210,
    'VP, Digital': 255,
    'SVP, Digital': 300,
    'Creative Technologist': 200
  },
  'Blended': {
    // All roles use the blended rate of 165
    'Account Coordinator': 165,
    'Account Executive': 165,
    'Account Manager': 165,
    'Account Supervisor': 165,
    'Production Coordinator': 165,
    'Production Executive': 165,
    'Production Manager': 165,
    'Production Supervisor': 165,
    'Production Director': 165,
    'Sr. Production Director': 165,
    'Account Director': 165,
    'Senior Account Director': 165,
    'Managing Director': 165,
    'Vice President': 165,
    'Sr Vice President': 165,
    'Executive Vice President': 165,
    'Designer': 165,
    'Sr Designer': 165,
    'Asc Design Director': 165,
    'Design director': 165,
    'Sr Design Director': 165,
    'VP, Design': 165,
    '3D Designer': 165,
    'Sr 3D Designer': 165,
    'Associate 3D Design Director': 165,
    '3D Design Director': 165,
    'Copywriter': 165,
    'Conceptor': 165,
    'Creative': 165, // Maps to same rate as Conceptor
    'Associate Creative Director': 165,
    'Creative Director': 165,
    'Group Creative Director': 165,
    'Executive Creative Director': 165,
    'SVP, Creative': 165,
    'Producer': 165,
    'Sr Producer': 165,
    'Editor': 165,
    'Sr Editor': 165,
    'Animator': 165,
    'Colorist': 165,
    'Post Production Lead': 165,
    'Head of Production': 165,
    'VP, Studio': 165,
    'VP, Strategy & Planning': 165,
    'Sr Director, Strategy / Planning': 165,
    'Director, Strategy / Planning': 165,
    'Sr Strategist / Planner': 165,
    'Strategist / Planner': 165,
    'Jr Strategist / Planner': 165,
    'MD, Shopper': 165,
    'Sr. Director, Shopper': 165,
    'Account Director, Shopper': 165,
    'Account Supervisor, Shopper': 165,
    'Account Manager, Shopper': 165,
    'Account Executive, Shopper': 165,
    'Coordinator, Shopper': 165,
    'Executive Creative Director, Shopper': 165,
    'Creative Director, Shopper': 165,
    'Associate Creative Director, Shopper': 165,
    'Sr. Design Director, Shopper': 165,
    'Art Director, Shopper': 165,
    'Sr. Designer, Shopper': 165,
    'Designer, Shopper': 165,
    'Coordinator, Creator': 165,
    'Specialist, Creator': 165,
    'Manager, Creator': 165,
    'Supervisor, Creator': 165,
    'Associate Director, Creator': 165,
    'Director, Creator': 165,
    'MD, Creator': 165,
    'Coordinator, Social': 165,
    'Specialist, Social': 165,
    'Manager, Social': 165,
    'Supervisor, Social': 165,
    'Director, Social': 165,
    'Managing Director, Social': 165,
    'Coordinator, Media': 165,
    'Coordinator, SEM': 165,
    'Executive, Media': 165,
    'Manager, Media': 165,
    'Manager, SEM': 165,
    'Supervisor, Media': 165,
    'Asc Director, Media': 165,
    'Director, Media': 165,
    'VP, Media': 165,
    'Jr. Developer': 165,
    'Mid Developer': 165,
    'Sr. Developer': 165,
    'UX Designer': 165,
    'Sr UX Designer': 165,
    'Jr Digital Project Manager': 165,
    'Digital Project Manager': 165,
    'Sr Digital Project Manager': 165,
    'Director, Digital': 165,
    'VP, Digital': 165,
    'SVP, Digital': 165,
    'Creative Technologist': 165
  }
};

// Get all unique roles from all rate cards
export const getAllRoles = (): string[] => {
  const allRoles = new Set<string>();
  
  Object.values(RATE_MAPPING_2025).forEach(rateCard => {
    Object.keys(rateCard).forEach(role => {
      allRoles.add(role);
    });
  });
  
  return Array.from(allRoles).sort();
};

// Get roles by department
export const getRolesByDepartment = (department: string): string[] => {
  const departmentRoles: { [key: string]: string[] } = {
    'Accounts': [
      'Account Coordinator',
      'Account Executive', 
      'Account Manager',
      'Account Supervisor',
      'Account Director',
      'Senior Account Director',
      'Production Coordinator',
      'Production Executive',
      'Production Manager',
      'Production Supervisor',
      'Production Director',
      'Sr. Production Director',
      'Managing Director',
      'Vice President',
      'Sr Vice President',
      'Executive Vice President'
    ],
    'Design': [
      'VP, Design',
      'Design Director',
      '3D Design Director',
      'Sr Designer',
      'Sr 3D Designer',
      'Asc Design Director',
      'Asc 3D Design Director',
      'Designer',
      '3D Designer'
    ],
    'Creative': [
      'Copywriter',
      'Creative',
      'Associate Creative Director',
      'Creative Director',
      'Group Creative Director',
      'Executive Creative Director',
      'SVP, Creative'
    ],
    'Studio': [
      'Producer',
      'Sr Producer',
      'Editor',
      'Sr Editor',
      'Animator',
      'Colorist',
      'Production Coordinator',
      'Post Production Lead',
      'Head of Production',
      'VP, Studio'
    ],
    'Strategy': [
      'Jr Strategist / Planner',
      'Strategist / Planner',
      'Sr Strategist / Planner',
      'Director, Strategy / Planning',
      'Sr Director, Strategy / Planning',
      'VP, Strategy & Planning'
    ],
    'Omni Shopper': [
      'Coordinator, Shopper',
      'Account Executive, Shopper',
      'Account Manager, Shopper',
      'Account Supervisor, Shopper',
      'Account Director, Shopper',
      'Sr. Director, Shopper',
      'MD, Shopper',
      'Designer, Shopper',
      'Sr. Designer, Shopper',
      'Art Director, Shopper',
      'Sr. Design Director, Shopper',
      'Associate Creative Director, Shopper',
      'Creative Director, Shopper',
      'Executive Creative Director, Shopper'
    ],
    'Creator': [
      'Coordinator, Creator',
      'Specialist, Creator',
      'Manager, Creator',
      'Supervisor, Creator',
      'Associate Director, Creator',
      'Director, Creator',
      'MD, Creator'
    ],
    'Social': [
      'Coordinator, Social',
      'Specialist, Social',
      'Manager, Social',
      'Supervisor, Social',
      'Director, Social',
      'Managing Director, Social'
    ],
    'Media': [
      'Coordinator, Media',
      'Coordinator, SEM',
      'Executive, Media',
      'Manager, Media',
      'Manager, SEM',
      'Supervisor, Media',
      'Asc Director, Media',
      'Director, Media',
      'VP, Media'
    ],
    'Digital': [
      'Jr. Developer',
      'Mid Developer',
      'Sr. Developer',
      'UX Designer',
      'Sr UX Designer',
      'Jr Digital Project Manager',
      'Digital Project Manager',
      'Sr Digital Project Manager',
      'Director, Digital',
      'VP, Digital',
      'SVP, Digital',
      'Creative Technologist'
    ]
  };
  
  return departmentRoles[department] || [];
};
